# Generated by Django 4.2.21 on 2025-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_name_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='w3r2ff', upload_to='images'),
            preserve_default=False,
        ),
    ]
