# Generated by Django 4.2.21 on 2025-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personaldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('billingaddress', models.TextField()),
                ('youraddress', models.TextField()),
                ('state', models.TextField()),
                ('district', models.TextField()),
                ('subdistrict', models.TextField()),
            ],
        ),
    ]
